
CONTEXT_ID     = core0.0
GENERIC_BINARY = false
ISSUE_WIDTH    = 8
BORROW         = 1.0.3.2.5.4.7.6
LANECONFIG     = 7B191919
BUNDLE_ALIGN   = 2

include /home/user/workspace/tools/scripts/compile.makefile
