
CONTEXT_ID     = core0.1
GENERIC_BINARY = true
ISSUE_WIDTH    = 8
BORROW         = 1.0.3,0.2,1.5,2.4,3.7,4.6,5
LANECONFIG     = 7333733B
BUNDLE_ALIGN   = 8

include /home/user/workspace/tools/scripts/compile.makefile
