
CONTEXT_ID     = core0.1
GENERIC_BINARY = true
ISSUE_WIDTH    = 8
BORROW         = 1.0.3.2.5.4.7.6
LANECONFIG     = 733B733B
BUNDLE_ALIGN   = 4

include /home/user/workspace/tools/scripts/compile.makefile
